### ISSUE TITLE
Problem installing ProQEXAFS-GUI

### ISSUE THREAD

**Issue by stnrl** [ClarkAH/ProXAS-GUI#2]
I tried following the installation described in the manual (the file  "ProXAS_GUI_Manual.docx"). After installing ANACONDA, however, the guide says to install xraylarch with the following command: 
`conda install –c GSECARS xraylarch` but it does not work. 

I did try to install xraylarch according to xraylarch website but after installing it, the script still did not work. it raises the following error: 
`Traceback (most recent call last):
  File "d:\ProXAS-2.43\ProXAS_v2.43.py", line 21, in <module>
    from larch_plugins.xafs import xftf, ftwindow, pre_edge, autobk, xftr
ModuleNotFoundError: No module named 'larch_plugins'`

Thank you for the help.
Cheers,

**Comment by ClarkAH** [comment]
the new command for this from anaconda should be:
conda install -c newville xraylarch
